server:
  port: 8899

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://rm-wz9xqe04o3v4y20sj1o.mysql.rds.aliyuncs.com/yaobili-business-company?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: ybl2018
    password: ybl2018@

#日志级别配置
logging:
  level:
    root: warn
    com.mybaties.plus.demo.mybatiesplusdemo.mapper: trace
  pattern:
    console: '%p%m%n'

